### ISSUE TITLE
Document differences as compared `cpan -g` or `sourcepan`

### ISSUE THREAD

**Issue by leonerd** [michal-josef-spacek/App-CPAN-Get#1]
There are already scripts to "just grab a tarball from CPAN". Firstly, `cpan` itself can do this:

```
$ cpan -g Some::Module
```

Secondly, my [`App-sourcepan`](https://metacpan.org/pod/distribution/App-sourcepan/bin/sourcepan) can do that, along with unpacking and initializing a revision control directory within it:

```
$ sourcepan --git Some::Module
```

At first glance it isn't clear how your script differs from those.

Perhaps you could add a `=head1 SEE ALSO` section to draw attention to these, and explain the difference?

**Comment by michal-josef-spacek** [comment]
Hi Paul,

Thanks for your examples. I was looking to cpanm without success in this functionality.

I improved doc, 0.02 version.
